### ISSUE TITLE
mouse movements bug

### ISSUE THREAD

**Issue by benmonro** [FormidableLabs/webpack-dashboard#16]
I get a strange behavior when I move my mouse around the terminal. I've tried this in fish and oh my zsh:  
![image](https://cloud.githubusercontent.com/assets/399236/17673990/626ca090-62d8-11e6-8de8-199606c3dc26.png)

**Comment by kenwheeler** [comment]
What terminal type are you using?

**Comment by akre54** [comment]
Getting the same. I'm using iTerm2 in "Full-Width Top of Screen" ("guake") mode.

**Comment by akre54** [comment]
My dev start script is `"nodemon server --watch server --exec babel-node --plugins transform-es2015-modules-commonjs,transform-object-rest-spread` if that makes any difference

**Comment by sameer-bridg** [comment]
Also experience the same issue.

**Comment by kenwheeler** [comment]
What do your settings look like? here are mine:

![screen shot 2016-08-15 at 3 54 29 pm](https://cloud.githubusercontent.com/assets/286616/17677407/a1fa2c1e-6300-11e6-988e-d88eaf7add73.png)

**Comment by theverything** [comment]
I'm having the same issue and my iTerm settings are the same as yous @kenwheeler

**Comment by benmonro** [comment]
I'm just using plain old terminal on mac @kenwheeler .  I am using oh-my-zsh.  Tried it on that as well as fish.  both have the same issue.

**Comment by eschaefer** [comment]
What's interesting for me is that the bug continues in iTerm2 after I kill the dev server as well.

**Comment by codejunkienick** [comment]
I've got the same issue with Termite on Arch Linux.

**Comment by kenwheeler** [comment]
@akre54 I can reproduce if I run with nodemon. Is everyone here running nodemon?

**Comment by brandonmp** [comment]
Same, in `gnome-terminal` and in `tilda`

Ubuntu 16.04.1
bash v.  4.3.46(1)-release (x86_64-pc-linux-gnu) 

I don't think I'm running `nodemon`, unless it's included in the [react-redux-starterkit](https://github.com/davezuko/react-redux-starter-kit) i'm using--doesn't show up in processes

**Comment by kenwheeler** [comment]
yeah you're using nodemon if you are using that kit.

**Comment by kenwheeler** [comment]
Ok, nodemon is the culprit. Issue filed here: https://github.com/remy/nodemon/issues/890 , lets see what @remy has to say. Other suggestions certainly welcome.

**Comment by benmonro** [comment]
Yep we're using nodemon

**Comment by akre54** [comment]
It isn't just with nodemon though. Using babel-node without nodemon has the same issue. Both Terminal.app and iTerm2.

Our app prints debugging info to the console (like queries run), so maybe it's an issue with piping stdout?

**Comment by kenwheeler** [comment]
I tried babel-node and couldn't reproduce the mouse issue. Maybe I'll just capture stdout and try to filter out control statements.

**Comment by kenwheeler** [comment]
@akre54 do you know of a way I can identify external stdout?

**Comment by akre54** [comment]
Not that I'm aware of (short of running the script as a child proces). I'm going to give #27 a try, will let you know how that goes.

**Comment by kenwheeler** [comment]
That wont fix the nodemon issue. It'll work for child processes that use console, but for anything that uses stdout.write it'll still leak. Whats even stranger is, when using nodemon, if I exit, the server stays running.

**Comment by akre54** [comment]
Right. I'm wondering if this is useful at all? https://github.com/remy/nodemon#pipe-output-to-somewhere-else

**Comment by kenwheeler** [comment]
Are you running nodemon using the node api?

**Comment by akre54** [comment]
I pulled in #27 and it seems to be working to redirect my query logging to the log window (I had to reorder some stuff so that Dashboard was set up before anything got logged). So A+ on that.

I'm still getting the mouse bug with nodemon and plain babel-node too. I'm running the nodemon executable (cli). I was thinking I could create an intermediate script that runs nodemon from the node-api.

**Comment by edorivai** [comment]
Same here as @brandonmp.
Running:

```
Ubuntu Gnome 16.04.1 LTS, 64-bit
GNU bash, version 4.3.46(1)-release (x86_64-pc-linux-gnu)
```

Express with `webpack-dev-middleware` and `webpack-hot-middleware`. Dashboard seems to we working fine, apart from this mouse-event printing.

**Comment by zrosenbauer** [comment]
Also getting this issue, I'll get my env details and pass along.

**Comment by kenwheeler** [comment]
Can you guys give this a shot https://github.com/FormidableLabs/webpack-dashboard/pull/50

**Comment by eschaefer** [comment]
@kenwheeler unfortunately for [my case](https://github.com/FormidableLabs/webpack-dashboard/issues/16#issuecomment-239951162), https://github.com/FormidableLabs/webpack-dashboard/pull/50 did not resolve the issue.

**Comment by kenwheeler** [comment]
@eschaefer have you tried zsh instead of bash?

**Comment by eschaefer** [comment]
@kenwheeler just tried zsh too, and the problem is the same.
```
$ zsh --version
zsh 5.2 (x86_64-apple-darwin15.6.0)
```

**Comment by kenwheeler** [comment]
@eschaefer can I see your iterm settings page like i posted above? Also, how are you running the dashboard? Can i see a gist of your whole setup from package.json to your server/webpack config?

**Comment by eschaefer** [comment]
@kenwheeler 

iTerm settings:
<img width="556" alt="screen shot 2016-08-17 at 11 50 13 am" src="https://cloud.githubusercontent.com/assets/547148/17748995/cbf2c320-6470-11e6-94f7-7f7e714a4bb3.png">

Dashboard is being launched from an npm script (`npm run dev`):
```
"dev": "cross-env NODE_ENV=development sh scripts/dev",
```

and the bash script `scripts/dev` looks like:
```
#!/bin/sh
./node_modules/.bin/webpack --config webpack/webpack.server.config.js --progress --silent
./node_modules/.bin/webpack --watch --devtool inline-source-map  --silent --config webpack/webpack.server.config.js &
./node_modules/.bin/webpack-dev-server --hot --silent --no-info --config webpack/webpack.client.config.js &

cd assets
../node_modules/.bin/nodemon -q server.generated.js

kill %2
kill %1
```

and webpack dev server config is: 
```
const webpack = require('webpack');
const autoprefixer = require('autoprefixer');
const shared = require('./webpack.shared');
const Dashboard = require('webpack-dashboard');
const DashboardPlugin = require('webpack-dashboard/plugin');
const dashboard = new Dashboard();

require('dotenv').config({
	silent: true,
	path: './../.env',
});

module.exports = {
	debug: true,
	devtool: '#cheap-eval-source-map',
	name: 'browser',
	target: 'web',
	
	entry: [
		'webpack/hot/only-dev-server',
		'babel-polyfill',
		'./src/scripts/utils/Modernizr.js',
		'./src/scripts/client.js',
	],
	
	output: {
		publicPath: 'http://localhost:8080/assets/',
		path: './public/assets',
		filename: '[name].bundle.js',
		sourceMapFilename: '[name].map',
		quiet: true,
	},

	module: {
		loaders: shared.commonLoaders.concat([
			{
				test: /\.less$/,
				loader: 'style!css!postcss!less',
			},
		]),
	},

	postcss: () => [autoprefixer],

	resolve: shared.commonResolve,

	plugins: shared.plugins.concat([
		new webpack.ProvidePlugin({
			React: 'react',
		}),
		new DashboardPlugin(dashboard.setData),
	]),
};
```

**Comment by kenwheeler** [comment]
Try the new approach in #50, look at the readme updates and use the webpack-dashboard bin in your npm scripts

**Comment by eschaefer** [comment]
@kenwheeler sorry, totally overlooked the readme updates... updated the gist.

When I run this task alone, it's fine:
```
./node_modules/.bin/webpack-dashboard -- ./node_modules/.bin/webpack-dev-server --hot --silent --no-info --config webpack/webpack.client.config.js
```

When I run the full bash script with parallel `webpack` tasks, then the mouse movement characters get dumped into the terminal.

**Comment by kenwheeler** [comment]
what if you put the dashboard first

**Comment by remy** [comment]
I'm pretty confident that the PR I've raised against nodemon (expected to
land in nodemon@1.10.1) fixes this.

**Comment by kenwheeler** [comment]
This should be fixed in the latest release

**Comment by remy** [comment]
This is back as I had to revert the change. It kinda blew up *everyone's* use of nodemon! I'll keep investigating. I know what the issue is, the child process is `setRaw(true)` but I can't detect and forward that from nodemon (though I'm trying stuff).

**Comment by edorivai** [comment]
I'm still getting the characters printed on mouse events. Using the same environment as before, now with the new setup which runs the `webpack-dashboard` binary.

For your convenience:

```
Ubuntu Gnome 16.04.1 LTS, 64-bit
GNU bash, version 4.3.46(1)-release (x86_64-pc-linux-gnu)
```

**Comment by mnzt** [comment]
Experiencing this issue on my system with the following details:

```
GNU bash, version 4.3.46(1)-release (x86_64-unknown-linux-gnu)
Arch Linux x86_64
i3 version 4.12-non-git
termite v11
```

**Comment by tom76kimo** [comment]
After updating `nodemon` and `webpack-dashboard`, still encounter with this issue as well.

**Comment by davefedele** [comment]
Changing iterm2 'report terminal type' to ANSI stops the mouse movements bug.

However, now I can't scroll :(

**Comment by cimi** [comment]
> Changing iterm2 'report terminal type' to ANSI stops the mouse movements bug.

I can confirm this. It is inconvenient, though.

I'm running it on OSX 10.10.5 with iTerm2, settings identical to the ones recommended on this post. The project was bootstrapped from [react-redux-starter-kit](https://github.com/davezuko/react-redux-starter-kit) about six months ago. I've tried plugging in the dashboard via the recommended way (through the binary).

This issue should probably be re-opened since the issue still persists.

**Comment by timpler** [comment]
It happens when there are more than 1 processes active in one console 'thread'. 

For example, in my `package.json`, I've got commands: 

```
  "scripts": {
    "start": "node server.js",
    "lint": "eslint src",
    "gulp": "gulp",
    "dev": "gulp | webpack",
    "webpack": "webpack-dashboard -- node server.js"
  },
```

If I call `npm run dev` - issue occurs (there is also `gulp` command running). If I run `npm run webpack` - there is no issue (`webpack-dashboard` is running alone).

**Comment by flipflopsandrice** [comment]
Indeed, as @pietrasiak noticed, it happens when starting two processes in one thread. 
Tested in Terminator, Guake and GNOME Terminal. All with zsh.

```json
"scripts": {
  "serve:dev": "webpack-dashboard -- webpack-dev-server --open --env dev & cd node_modules/api-mocks && DEBUG=-* yarn run start",
}
```
Using a package like [concurrently](https://github.com/kimmobrunfeldt/concurrently) makes no difference (obviously).

**Comment by kenwheeler** [comment]
@flipflopsandrice you can run it standalone now, this should only happen using the old syntax where you pass a process. Otherwise it runs on its own and gets data via sockets. Doing it the old way, shown above, does some weird thing with stdout

**Comment by flipflopsandrice** [comment]
@kenwheeler Thanks, I fixed it by adding a separate npm script:

```json
"scripts": {
  "dev:dashboard": "webpack-dashboard -- npm run serve:dev",
  "serve:dev": "webpack-dev-server --open --env dev & cd node_modules/api-mocks && DEBUG=-* yarn run start",
}
```
