### ISSUE TITLE
can't start dashboard

### ISSUE THREAD

**Issue by luisrudge** [FormidableLabs/webpack-dashboard#83]
```
λ npm start

> package@0.0.0 start c:\git\rr\cis-v2-frontend\src
> webpack-dashboard -- webpack-dev-server --hot --inline --colors --no-info

internal/process.js:106
      throw errnoException(err, 'kill');
      ^

Error: kill ESRCH
    at exports._errnoException (util.js:893:11)
    at process.kill (internal/process.js:106:13)
    at process.<anonymous> (c:\git\rr\cis-v2-frontend\src\node_modules\webpack-dashboard\bin\webpack-dashboard.js:73:11)
    at emitOne (events.js:95:20)
    at process.emit (events.js:182:7)
    at process.exit (internal/process.js:79:15)
    at Screen.<anonymous> (c:\git\rr\cis-v2-frontend\src\node_modules\webpack-dashboard\dashboard\index.js:29:13)
    at Screen.EventEmitter._emit (c:\git\rr\cis-v2-frontend\src\node_modules\blessed\lib\events.js:94:20)
    at Screen.EventEmitter.emit (c:\git\rr\cis-v2-frontend\src\node_modules\blessed\lib\events.js:114:17)
    at Program.<anonymous> (c:\git\rr\cis-v2-frontend\src\node_modules\blessed\lib\widgets\screen.js:593:12)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.11.0
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! package@0.0.0 start: `webpack-dashboard -- webpack-dev-server --hot --inline --colors --no-info`
npm ERR! Exit status 1
```

![image](https://cloud.githubusercontent.com/assets/941075/17818993/5758b7ec-661c-11e6-960a-746caa31f7ef.png)

====================================================================

###### Please provide a gist of relevant files

1. package.json (specifically the script you are using to start the dashboard)
`"start": "webpack-dashboard -- webpack-dev-server --hot --inline --colors --no-info",`
2. webpack.config.js
```js
import DashboardPlugin from 'webpack-dashboard/plugin';

plugins: [
    new DashboardPlugin(),
    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.optimize.DedupePlugin(),
    new ExtractTextPlugin('bundle.css'),
    new HtmlWebpackPlugin({
      template: './app/index.html',
      hash: true,
      filename: 'index.html',
      inject: 'body'
    }),
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: json(isProd ? 'production' : 'development')
      },
      __DEV__: !isProd,
      __PROD__: isProd
    })
  ],
```
3. index.js (Your express based dev server, if applicable)

====================================================================

###### More Details

- What operating system are you on? **Windows**
- What terminal application are you using? **cmder**
- What version of webpack-dashboard are you using? **0.1.4**

**Comment by kenwheeler** [comment]
I just pushed out 0.1.5 can you try with that?

**Comment by kenwheeler** [comment]
Also, if you just run `webpack-dev-server --hot --inline --colors --no-info` , does it work?

**Comment by luisrudge** [comment]
0.1.5 still doesn't work.

running just `webpack-dev-server --hot --inline --colors --no-info` works, even with the DashboardPlugin inside the plugins array

**Comment by kenwheeler** [comment]
hmmm. what about if you take out inline and hot?

**Comment by kenwheeler** [comment]
Looks like its related to this https://github.com/nodejs/node-v0.x-archive/issues/8795

**Comment by luisrudge** [comment]
Nope.
`"start": "webpack-dashboard -- webpack-dev-server",`
`"start": "webpack-dashboard -- webpack-dev-server --colors --no-info",`

Tried both

**Comment by luisrudge** [comment]
I'm not running powershell though

**Comment by kenwheeler** [comment]
Its windows though right?

**Comment by luisrudge** [comment]
Yes

**Comment by kenwheeler** [comment]
Can you do me a huge favor. Can you go into your node_modules/webpack-dashboard and go to the bin folder. Can you wrap line 68 in a try catch or an `if (-child.pid)` , and let me know if it works. Sorry, I dont have a windows testing env.

**Comment by luisrudge** [comment]
```js
process.on("exit", function () {
  try {
    process.kill(-child.pid);
  }
  catch (e) {
    console.error('can\'t kill process', e);
  }
});
```

```
> webpack-dashboard -- webpack-dev-server --colors --no-info

can't kill process { [Error: kill ESRCH] code: 'ESRCH', errno: 'ESRCH', syscall: 'kill' }
```

**Comment by luisrudge** [comment]
Still doesn't work though

**Comment by kenwheeler** [comment]
How about if you remove that line. and if that doesn't work, remove `{detached: true}`

**Comment by luisrudge** [comment]
When I remove detached:

![image](https://cloud.githubusercontent.com/assets/941075/17820325/a34306d4-6622-11e6-8a11-d36f8e25dfe9.png)

**Comment by kenwheeler** [comment]
do you have webpack-dev-server installed locally as a dev dep?

**Comment by luisrudge** [comment]
Yes
```
λ cat node_modules\webpack-dev-server\package.json | grep version
        "type": "version"
    "type": "version"
  "version": "1.14.1"
```

**Comment by luisrudge** [comment]
here's my full webpack config: https://gist.github.com/luisrudge/67b1a17d3a9703b82b21432a2ea6fd6a

**Comment by shihaoli** [comment]
![error](https://cloud.githubusercontent.com/assets/7623006/17823130/d4548aa8-660f-11e6-8377-0847b45c6ec3.PNG)

same here.

**Comment by kenwheeler** [comment]
That error says that the address is in use?

**Comment by cristian-sima** [comment]
Same also for me, on Windows 10

![image](https://cloud.githubusercontent.com/assets/12199042/17836745/d8780686-67a5-11e6-8269-b4aebc6991cc.png)

**Comment by cristian-sima** [comment]
Here is the log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Cristian\\AppData\\Roaming\\npm\\node_modules\\npm3\\node_modules\\npm\\cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.6
3 info using node@v6.3.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle cube@1.0.0~predev: cube@1.0.0
6 silly lifecycle cube@1.0.0~predev: no script for predev, continuing
7 info lifecycle cube@1.0.0~dev: cube@1.0.0
8 verbose lifecycle cube@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle cube@1.0.0~dev: PATH: C:\Users\Cristian\AppData\Roaming\npm\node_modules\npm3\node_modules\npm\bin\node-gyp-bin;W:\go-workspace\src\github.com\cristian-sima\cube\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Cristian\bin;C:\ProgramData\Oracle\Java\javapath;W:\Developer;C:\Program Files\nodejs;C:\Program Files\Git\usr\bin;C:\Windows\System32;W:\go-workspace\src\github.com\smartystreets\goconvey;C:\Program Files (x86)\SMLNJ\bin;W:\XAMPP\php;C:\Go\bin;C:\Program Files\nodejs;C:\Users\Cristian\AppData\Local\atom\bin;C:\Users\Cristian\AppData\Roaming\npm
10 verbose lifecycle cube@1.0.0~dev: CWD: W:\go-workspace\src\github.com\cristian-sima\cube
11 silly lifecycle cube@1.0.0~dev: Args: [ '/d /s /c',
11 silly lifecycle   'webpack-dashboard -c -p 3001 -- webpack-dev-server --inline --hot' ]
12 silly lifecycle cube@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle cube@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: cube@1.0.0 dev: `webpack-dashboard -c -p 3001 -- webpack-dev-server --inline --hot`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Cristian\AppData\Roaming\npm\node_modules\npm3\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Cristian\AppData\Roaming\npm\node_modules\npm3\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid cube@1.0.0
16 verbose cwd W:\go-workspace\src\github.com\cristian-sima\cube
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Cristian\\AppData\\Roaming\\npm\\node_modules\\npm3\\node_modules\\npm\\cli.js" "run" "dev"
19 error node v6.3.1
20 error npm  v3.10.6
21 error code ELIFECYCLE
22 error cube@1.0.0 dev: `webpack-dashboard -c -p 3001 -- webpack-dev-server --inline --hot`
22 error Exit status 1
23 error Failed at the cube@1.0.0 dev script 'webpack-dashboard -c -p 3001 -- webpack-dev-server --inline --hot'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the cube package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dashboard -c -p 3001 -- webpack-dev-server --inline --hot
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs cube
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls cube
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by kenwheeler** [comment]
Fixed in 0.1.7

**Comment by cristian-sima** [comment]
No, it is not fixed.

This is what I am seeing:

![image](https://cloud.githubusercontent.com/assets/12199042/17882133/36990c9c-6913-11e6-99a2-429a0c19aeb2.png)

**Comment by jedirandy** [comment]
The fix is about processes not being correctly killed when you quit the dashboard, resulting in startup issues since the http port is being used by the previously created orphan process. So it has been fixed. From your screenshots,  you might want to check #94 or similar issues?

**Comment by cristian-sima** [comment]
Yes. Closing the process works. Thanks @jedirandy
